### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by jensdevbeule** [wp-sync-db/wp-sync-db#154]
Hello

Why not trying to have an automated push/pull in the plugin features?

Sincerely

**Comment by thedonquixotic** [comment]
@jensdevbeule try this fork instead https://github.com/outlandishideas/wp-sync-db

**Comment by slang800** [comment]
@jensdevbeule - because that's a lot of work, and I don't use PHP or Wordpress anymore. If you're able to implement that I'd be more than happy to give you this repo.

**Comment by jcklpe** [comment]
@slang800 No worries! (open source people don't owe users and are being generous with their time :smile:   )I would suggest rather opening up the repo to contributors in the spirit of this idea: http://felixge.de/2013/03/11/the-pull-request-hack.html

Or at least giving repo rights to @corysimmons https://github.com/corysimmons/wp-sync-db or @fahimxyz  https://github.com/fahimxyz/wp-shift-db who have the most advanced forks of the project from my research. Or maybe @outlandishideas would being willing to take up the mantle in a more official capacity. 

The current problem as it is, is that due to the way Github works it's very hard to find which forks are being actively developed.

**Comment by jcklpe** [comment]
EDIT: oops, I meant to say open source people DON'T owe users. Whoops. You've been generous your time in the past with this stuff and I don't want to seem like I'm being entitled, I just want to help others find what they're looking for and maybe people can continue the project and keep it going.
