### ISSUE TITLE
Is WP Sync DB secure and maintained?

### ISSUE THREAD

**Issue by richvida** [wp-sync-db/wp-sync-db#36]
Thank you for providing this plugin. It has worked, without issue, for me and is a great alternative to dropping $200 bucks for WP Migrate DB Pro.

However, I'm concerned about the security of it. Is it generally safe to keep this plugin installed on a production environment, or should I only install it when I intend on doing database migration?

Thanks,
Rich

**Comment by slang800** [comment]
I maintain it in my free time, updating it as new releases of WP Migrate DB Pro come out, and the community is welcome to review & improve the code-base.

It's basically the same code as WP Migrate DB Pro, but with the license-checker and analytics removed. So I would say it's _more_ safe, because your personal information is never reported to Delicious Brains (or me), and the code is out in the public, able to be audited by anyone and everyone. 

I suppose it has a smaller attack surface because it never connects to those analytics or license checking servers... although tbh they weren't particularly promising attack vectors to begin with.

I think it's generally safe to keep it installed. If you want to be extra safe, you can disable push/pull requests in the settings tab, or disable the whole plugin in the plugins menu, when you're not using it.

**Comment by option8films** [comment]
On that note, speaking on behalf of the many users of your plugin, I want to thank you for your hard work and continued effort to maintain this valuable plugin. Your contribution to the WordPress Development community is appreciated. Cheers!

**Comment by slang800** [comment]
Thanks!
