### ISSUE TITLE
Cannot use "pull" for migration

### ISSUE THREAD

**Issue by ygspasov** [wp-sync-db/wp-sync-db#52]
When I try to migrate a database from localhost to my live site by using "Pull" and paste the connection info into the "Pull" section of the live site, the plugin displays the following error:

There was a problem with the AJAX request, we were expecting a serialized response, instead we received:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

I have no problem migrating the database when I push it from the localhost to my live site.

**Comment by SmashBrando** [comment]
Your live site cannot see your local host since it's on your local machine, while your local host can see outward to your production site on the internet.

You would need to push pull from sites that are hosted. 

I recommend setting up a dev server with the domain dev.yoursite.com. You can make your edits there and then you can push pull when needed.

**Comment by ygspasov** [comment]
Thank you for the info.

**Comment by slang800** [comment]
closing because it looks like @SmashBrando solved your problem.
