### ISSUE TITLE
Unable to solve error #137

### ISSUE THREAD

**Issue by colmoneill** [wp-sync-db/wp-sync-db#56]
When attempting a push migration I get an error 137:
```
Invalid content verification signature, please verify the connection information on the remote site and try again. (#137)
```

Here is the error log:
```
site_url(): http://localhost/wp2
home_url(): http://localhost/wp2
Table Prefix: wp_
WordPress: WP4.2.2
Web Server: Apache/2.4.7 (Ubuntu)
PHP: 5.5.9-1ubuntu4.9
MySQL: 5.5.43-0ubuntu0.14.04.1
ext/mysqli: yes
WP Memory Limit: 40M
WPSDB Bottleneck: 1 MB
Debug Mode: No
WP Max Upload Size: 2 MB
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Error Log: 
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014
cURL: Enabled

Active Plugins:
Polylang (v1.7.3) by Frédéric Demarle
Advanced Custom Fields (v4.4.1) by Elliot Condon
Booking System PRO (v2.0.8) by Dot on Paper
Master Slider (v2.2.1) by averta
Side Matter (v1.4) by Christopher Setzer
WP Sync DB (v1.5) by Sean Lang
```

Could the issue be linked to me using http://localhost/wp2 as a local URL?

I've tried resetting the connection info api key many times to no avail.

Also, wondering about #47 and don't really understand the idea of keeping the paid version in delicious-brain branch? I see there are more recent commits there. Is the master branch dead?

Thanks!

**Comment by slang800** [comment]
Since you have polylang active, I'm gonna assume that this is the same issue as #62, and what's addressed by #74. You posted an issue first, but the other one has more comments on it, so I'm gonna close this one.

As for #47, I've got the paid version in another brach because it's what master is based off of, and I just haven't gotten around to copying over the updates from that branch and merging them with the updates from wp-sync-db.
