### ISSUE TITLE
wp-sync-db really "sync"?

### ISSUE THREAD

**Issue by juniovitorino** [wp-sync-db/wp-sync-db#60]
Hi folks, I’ve facing a problem with our WordPress clients, that is keep two databases synced easily without lost data, when I say “sync” I say two WordPress sites running in production receiving different contents (posts, custom posts, custom fields, …) and being merged both without lost any indivudual information between them.

wp-sync-db could solve this?

**Comment by slang800** [comment]
Nah - it's not good for merging data... MySQL in general isn't good at that. It's just called wp-sync-db because delicious brains trademarked the name wp-migrate-db after I forked it.

You're probably looking for [MySQL clustering](https://dev.mysql.com/doc/refman/5.0/en/mysql-cluster-overview.html), or something of that nature.
