### ISSUE TITLE
Dead Project?

### ISSUE THREAD

**Issue by Ramblurr** [wp-sync-db/wp-sync-db#76]
There hasn't been a release to this project in almost a year. Do the devs no longer have time or interest in maintaining it?

Is the project actively looking for a new maintainer?

**Comment by taddmencer** [comment]
I was wondering the same thing. This was going to be a "productivity saver" for me. Or that was my intention. Hopefully it's not deadware.

**Comment by mkaschke** [comment]
I hope it's not deadware because it is a really helpful plugin! Love it!

**Comment by mAAdhaTTah** [comment]
I still use it currently, but I haven't seen any updates on the project in a long time. It's a public "fork" of a paid plugin, so unless the original developer continues to pay for updates (or gets them through other means), it's hard to keep it updated. And this version never got the community traction the original developer was hoping for when he OS'd it.

**Comment by senlin** [comment]
Still works, but seems to be deadware indeed...

**Comment by slang800** [comment]
Kinda deadware... I haven't touched it in awhile since I don't use WordPress much & I don't have any particular desire to work with PHP. However, if you look in the [delicious-brains branch](https://github.com/wp-sync-db/wp-sync-db/tree/delicious-brains) you'll find the latest version from delicious-brains, and if someone would take the time to copy those changes over to the master branch (removing the DRM & copyrighted name), I'd be happy to accept the PR & release it.

**Comment by Ramblurr** [comment]
Looks like the [current delicious brains version is 1.5.3](https://deliciousbrains.com/wp-migrate-db-pro/doc/changelog/), but your branch is at 1.4.7. Do you have access to the latest GPLed version?

**Comment by konus1** [comment]
May be it is here https://github.com/deliciousbrains/wp-migrate-db 
Version-Numbers are different though.

**Comment by kochhase** [comment]
no, thats the normal Version, not the pro. I there anybody there, that can help with the version 1.5.3 pro?

**Comment by mindsize** [comment]
If you'd like updates, you should seriously consider buying the plugin from the original developer, since they employ the programmers that write the code AND they actually release updates. You can [purchase a license](https://deliciousbrains.com/wp-migrate-db-pro/pricing/) for Migrate DB Pro from [Delicious Brains](https://deliciousbrains.com/).

Disclaimer: I am a happy Delicious Brains customer that has supported their development efforts by purchasing their premium offering. For whatever reason, I like having support and updates.

**Comment by andrewmclagan** [comment]
Open source is 9 times out of 10 more secure, reliable and frequently updated. Simply power by numbers.

If you are a someone who hacks together wordpress themes and not actually developer then by all means you will need the support of professional developers. In that case buy the plugin.

Otherwise, if you are a developer you will be able to customize or even contribute to this project. So please do so.

**Comment by mindsize** [comment]
Oh, I could contribute, and I do contribute to many commercially available plugins through their open source repositories. I just won't support blatant rip offs hiding behind the shield of GPL. Do something original with the code and build something off of it that isn't a direct copy and we'll talk.

**Comment by slang800** [comment]
@Ramblurr - nope, the subscription that I was using ran out. If anyone wants to donate a license key, that'd be fantastic.

**Comment by slang800** [comment]
@mindsize: That's actually kinda funny, because from my perspective it's delicious brains that is hiding _from_ the GPL. I'm disgusted to see them build atop WordPress - a free software project supported by a community of volunteers - and then make their code as close to proprietary as possible. Rather than giving back to the community that they stand on, they charge absurd yearly fees, build DRM into their product, and attempt to take me down with copyright.

I have no problem with them making money off their work, but the business model they've picked is completely antithetical to the ideals of free software.

**Comment by mindsize** [comment]
WordPress.com is built on GPL software. Do you have trouble with it, too?
They charge for support and updates plus added features that they've deemed
to be commercial. WordPress VIP. VaultPress. Akismet. WooCommerce. All
monetized on top of GPL code and owned by Automattic. And those are just
examples in the WordPress space. Free software means the code is open to
experimentation and expansion, not free to exploit the work of others as
you see fit. The free software ethos is that as a community we make better
software together than if it is all developed in a proprietary bubble. More
developers means more features, more bug fixes and more community.

You have added nothing of worth. This is a direct copy with a few lines of
code removed to remove the protections a software developer chose to put on
their premium offering. That's why premium isn't in the repo. It's not
intended to be free to use, you just have the freedom to develop against it
if you have a license.

They were entitled to enforce their copyright when you published using the
exact name of their software. That was a dumb move. And from the rhetoric
here, you're just out to get something without paying for it. Can someone
please donate a license so I can continue ripping them off? Everywhere in
the world with the exception of your warped view of "free software" that
would be considered theft.

I know you're not alone in this. The term free should never have been
attached to open source software because so many miserable cheapskates
misinterpret it. Not using the word free would make it so much easier for
the lazy, entitled few to grasp. Just for reference, this is the spirit in
which the GPL was created:
http://torquemag.io/2013/08/explaining-and-understanding-the-gnu-general-public-license-gpl/

So keep on ripping off companies that pay to develop software without
regard for how they pay their bills. Continue providing nothing of
additional value to the community. Never develop anything original, though,
Sean. I'd hate for someone else to do to you what you've done to Brad and
the team at Delicious Brains.

**Comment by andrewmclagan** [comment]
@mindsize if they wanted to make money from their project why would they open source it?

To get the free hours of work from other developers? WooCommerce has the best model: Open-Source  project and charge for extensions. There are many forks of WooCommerce, come on WooCommerce is a fork itself of an older project. Do you hear them complaining? 

Its simply the most blatant form of idiocy to open source a project then complain when people fork it... LOL

**Comment by mindsize** [comment]
WooCommerce is a fork that added value in the form of new, innovative code.
If they had just duplicated the repo and said "OK, we're good!" there would
have been outrage.

**Comment by mindsize** [comment]
Also, the model WooCommerce uses is the exact same model Delicious Brains
is using. The core plugin, without the features from premium, is free.
That's what they have in the repository. You've taken the premium features
from the "extension" product and are giving them away with the open source
portion of the code. That's why I have an issue with it. If you had written
your own code to replicate the premium features with your own unique twist
rather than pretty blatantly stating that all you've done is remove the
code to enforce the license, we wouldn't be having this conversation. Then,
it would be a derivative work. Right now, it's just a way to help others
not pay Delicious Brains for their premium plugin.

**Comment by mAAdhaTTah** [comment]
> if they wanted to make money from their project why would they open source it?

Delicious Brains didn't open source it. It's GPLed, which allows @slang800 to take his copy and open source it, if he chooses. There's a (huge) difference. The only open-source product here is a free product, which was "forked" into this repo, but isn't really the same product we're talking about.

> That's actually kinda funny, because from my perspective it's delicious brains that is hiding from the GPL.

No. None of this whatsoever. The GPL doesn't force you to give away your product; it gives the user of said product a set of rights over said product, including redistribution, as you've done here. It doesn't force anyone to open source their product, doesn't prevent anyone from charging for their product, doesn't prevent anyone from doing any of the things Delicious Brains is doing. They are well within their rights to do so, just as you're well within your rights to open source their software when you purchased it.

There are plenty of companies making money off the WordPress ecosystem, many of them functioning with a similar business model to DB. Plenty of them give back with open source software (like DB does) while selling more complicated software for money. There's no reason to target them; developers are allowed to make money off of open source software, and there isn't anything specific about DB's approach that makes it an outlier in the WordPress ecosystem.

I generally have no problem with open sourcing a paid plugin (if you were selling it, it would be another issue); the GPL gives you the right to do so, and as a hobbyist, I appreciate not having to spend hundreds to move databases from my personal websites around. But that attitude is 100%, Grade A, Bullshit. The people behind DB give back to the community in plenty of (free) ways. They have a podcast, a couple of free open source plugins, and a regular blog. They don't owe the community (or you) anything.

**Comment by slang800** [comment]
Whew, this got a bunch of replies! :smile: I'll start from the top and provide quotes, since there's a lot of different claims to address...

> WordPress.com is built on GPL software [...] They charge for support and updates plus added features that they've deemed to be commercial.

The original Wordpress.com was basically a cheap Wordpress hosting service. I think that it makes sense to charge for support and hosting, because having people there to answer questions costs money, and servers do too. I'm not sure what features they had that weren't free software... looking at their [list of plans](https://store.wordpress.com/plans/), it seems that the only restrictions they impose are limits on storage space, and some limited customization (presumably to prevent people from being able to execute arbitrary code on servers in the free tier). Nothing that you're not able to do on your own if you clone the Wordpress repo and install it on a server. And the new Wordpress.com seems to be available [here](https://github.com/Automattic/wp-calypso).

> WordPress VIP

Looks like [that](https://vip.wordpress.com/) is the same thing as Wordpress.com, but marketed to businesses. And I see that as a pretty ethical way to make money off of free software. They don't hide their code or stop others from being able to use and modify it, they just charge you for support and hosting, which means that you can take the code and switch to your own server if you ever want to.

> VaultPress

They seem to have the source code [posted here](https://wordpress.org/plugins/vaultpress/). I'm not sure if they have any non-free code running on their servers, and I don't see instructions on how to setup VaultPress on your own server displayed prominently, so I consider them "kinda shady", but not "fully unethical".

> Akismet

Akismet is (AFAIK) a proprietary spam filtering service, with a lightweight free plugin that acts as a client. I don't think Akismet should be distributed with Wordpress or used by anyone because it promotes vendor lockin and rejects basic freedom. Stallman makes some good points about it [here](http://www.gnu.org/philosophy/who-does-that-server-really-serve.en.html) and the [AGPL](http://www.gnu.org/licenses/agpl-3.0.en.html) does a pretty good job of addressing the problem.

> WooCommerce

Looks like the source is [here](https://github.com/woothemes/woocommerce) and they charge for support, so I'd give them a :+1:. I'm not sure what they're a fork of, but so long as they respect the GPL they're probably good. If they've got proprietary plugins then I'd advocate for freeing them like I did with WP-Migrate-DB-Pro.

> Free software means the code is open to experimentation and expansion, not free to exploit the work of others as you see fit.

Exactly! Unlike permissive licenses (like the Ex-pat / MIT), the GPL prevents companies from exploiting free software by using it to build proprietary apps that take away user freedoms. It ensures this by allowing people (like me) to redistribute and hack on all GPL'd code. It prevents companies (like Delicious Brains) from being able to treat their derivative works like proprietary code.

> The free software ethos is that as a community we make better software together than if it is all developed in a proprietary bubble. More developers means more features, more bug fixes and more community.

Sorta... Linus's Law ("given enough eyeballs, all bugs are shallow") is a nice side-effect of free software, but it's not the "ethos". Free software is about _freedom_, and that freedom is held above all else. We don't just make software free because of the benefits of an open community, but because that freedom is a moral imperative. Free access to knowledge is such a basic right, and a necessity for advancing society, that it doesn't really matter whether or not it improves software quality. This difference between motivations is generally expressed in the [difference between the terms "open source" and "free"](http://www.gnu.org/philosophy/open-source-misses-the-point.html), with "open source" being aimed at a more effective development methodology, and "free software" being motivated by ethics.

> You have added nothing of worth.

I certainly did make it easier to download and in my version you don't have to keep track of those pesky license keys, or worry about the software "phoning home". I'd say that's an improvement.

> This is a direct copy with a few lines of code removed to remove the protections a software developer chose to put on their premium offering.

Well, I needed to do a bit more than "a few lines" of modification, but yeah, that's pretty close. Also, developers shouldn't be able to force "protections" (DRM) upon a user. The freedoms that are ensured by the GPL should prevent developers from even trying because, inevitably, someone who knows their rights will come along and remove the DRM.

> That's why premium isn't in the repo. It's not intended to be free to use

Yeah, and not being free (or even gratis, for that matter) is why they are "completely antithetical to the ideals of free software" (quoting my earlier comment).

> You just have the freedom to develop against it if you have a license.

Actually, you're free to develop against it no matter what - they just make it look like you need a license key. In fact, that license key is just an arbitrary restriction that they put in the software.

> They were entitled to enforce their copyright when you published using the exact name of their software. That was a dumb move.

Yes, it was and I should have seen that coming. It seemed like it would fall under fair-use because I was using the copyrighted name "WP Migrate DB Pro" just to refer to the actual "WP Migrate DB Pro" code, rather than using their name on a new product, but I've talked to people who know more about this than me, and they say that copyright can still be enforced in that case.

But anyway, I mention the copyright claim because it seems to have been made specifically to remove the code, rather than address the actual issues in the claim (the use of their name and promotional copy). They made no attempt to resolve the issue personally and went straight for legal action.

> And from the rhetoric here, you're just out to get something without paying for it. Can someone please donate a license so I can continue ripping them off?

With regards to the license - yeah, I don't want to pay for it. It's like 200USD and I don't even use Wordpress in production anymore. I'm only keeping this up for the sake of the people who do use it.

> The term free should never have been attached to open source software...

Actually, it was "open source" that split off from "free software". While the term "free software" was coined back in 1986, "open source" didn't appear till 1998... The re-branding of the free software movement under the "open source" name was mostly to promote corporate buy-in by ignoring the ethical motivations in free software.

> ...because so many miserable cheapskates misinterpret it. Not using the word free would make it so much easier for the lazy, entitled few to grasp.

Yeah, the whole "free vs gratis" thing is a pain. I try to use "libre" in contexts where "free" isn't obvious, but it would be nice to have a better word.

> Never develop anything original, though, Sean. I'd hate for someone else to do to you what you've done to Brad and the team at Delicious Brains.

I'm quite alright with what I've done being done to me. Feel free to take any of my projects and modify or redistribute them. I wouldn't even really care if you took the proprietary code that I haven't released (the companies that I've written it for would, but I'm indifferent). I make my money by writing new software (which often is released freely), not by restricting the usage of software that's already been written.

-----

> If they wanted to make money from their project why would they open source it? [...] Its simply the most blatant form of idiocy to open source a project then complain when people fork it.

Well, they didn't really have a choice in the matter. They built upon a base of free software that is licensed specifically to prevent proprietary software from being created. This is usually where the accusations of the GPL being a "viral license" come from.

They're not idiots - they want to take from Wordpress while only fulfilling the bare-minimum requirements to comply with the GPL. And I don't think they're complaining out of surprise that this happened, they just don't want to lose money.

------

> which was "forked" into this repo, but isn't really the same product we're talking about.

I'm really sorry if the fact that this repo is a fork of wp-migrate-db has caused confusion. I was expecting wp-migrate-db-pro to share history and code with the repo I forked (giving the commit log a nice logical progression), but it turned out to be more of a spiritual successor.

> The GPL doesn't force you to give away your product [... It] doesn't prevent anyone from doing any of the things Delicious Brains is doing.

You're absolutely correct. However, I'm not saying that what they're doing is wrong from a legal basis. I'm saying that putting license-key based restrictions on their product is antithetical to the _spirit_ of the GPL. When I say "hiding from the GPL", I'm referring to the way that they avoid informing users of their rights. As of `1.4.7`, they don't even include the text of the GPL in their zipped distributions. On their product page & docs the only license I can find them talking about is the one that's used to "activate the product".

> The people behind [Delicious Brains] give back to the community in plenty of (free) ways. They have a podcast, a couple of free open source plugins, and a regular blog.

That's great, and they seem to [donate to charity](https://deliciousbrains.com/giving-back/) too. They're probably very nice people, but that doesn't excuse them from criticism.

**Comment by mindsize** [comment]
Well, since you obviously have a better grasp on GPL than the leaders and IP lawyers I've spoken with, continue doing what you're doing. I'll continue dual-licensing my projects to protect my IP.

**Comment by mindsize** [comment]
WooCommerce is a fork of JigoShop. Some extensions are free, most are not. All are GPL licensed.

The free software movement started because people wanted the freedom to modify the software they used in any way they wanted, whether that be to fix bugs, extend the software or port to a different language or operating system. Hacker mentality and commerce have never really gotten along, and I understand that, but the movement was never meant to stop people from making money off of their work. That is why most companies are charging for updates and support.

Let's face it. Software developers are going to want to make money off of their work and *GPL does not preclude them from doing so.* Complaining that people are building businesses on top of any GPL licensed product is honestly quite ludicrous.

This whole conversation started because I suggested that people who wanted your repo updated, a repo that has all but been abandoned, might want to support the developer that actually wrote the software you've posted here. I don't think that is an unreasonable suggestion, by any means. If they want the updates, they should go support the developer that wrote the software. You are actually doing the community a disservice by having old code that doesn't incorporate recent security patches available for download.

**Comment by slang800** [comment]
> Complaining that people are building businesses on top of any GPL licensed product is honestly quite ludicrous.

Yes, that position would be ludicrous, [if anyone were suggesting it](https://yourlogicalfallacyis.com/strawman). Like I said earlier, "I have no problem with them making money off their work, but the business model they've picked is completely antithetical to the ideals of free software". I'm not complaining _that_ they are making money off GPL'd code, I'm complaining about _how_ they are making money.

For example, making money by providing paid hosting / support is a good business model. Making money by putting arbitrary restrictions on the number of installations you can have on your own servers isn't a good model. Having people pay you to create new / custom software is usually harmless; sometimes even beneficial when you can release components of that software as FOSS. Having people pay you because your data is stuck on their service and moving it off that service is cost-prohibitive or impossible isn't harmless.

> This whole conversation started because I suggested that people who wanted your repo updated, a repo that has all but been abandoned, might want to support the developer that actually wrote the software you've posted here.

Yeah, your [first comment](https://github.com/wp-sync-db/wp-sync-db/issues/76#issuecomment-186270213) is fine. It kinda sounded like an ad, but I don't really care.

> You are actually doing the community a disservice by having old code that doesn't incorporate recent security patches available for download.

I don't see any security patches in the [changelog](https://deliciousbrains.com/wp-migrate-db-pro/doc/changelog/), but if there are any, feel free to PR. Also, based on Linus's Law, making the code available to the general public should increase the number of eyes and decrease the number of bugs... I don't know if that's happened here, but I think that making code public generally improves security.

**Comment by mAAdhaTTah** [comment]
Fundamentally, the "freedom" the GPL gives you, and the "free" in "free software", doesn't mean all software developed under the GPL needs to be given away for free. It means that, once you come into possession of said software, you have the freedom to do what you want with it. Selling GPL'd software has never been against the terms of the GPL, nor against the ethics of free software.

http://www.gnu.org/philosophy/selling.en.html

> Many people believe that the spirit of the GNU Project is that you should not charge money for distributing copies of software, or that you should charge as little as possible—just enough to cover the cost. This is a misunderstanding.

> Actually, we encourage people who redistribute free software to charge as much as they wish or can. If a license does not permit users to make copies and sell them, it is a nonfree license. If this seems surprising to you, please read on.

The idea that Delicious Brains is subject to any sort of criticism because they're selling GPL'd software is, as I said before,  100%, Grade A, Bullshit.

**Comment by slang800** [comment]
from http://www.gnu.org/philosophy/selling.en.html (a few paragraphs below your quote):

> People sometimes worry that a high distribution fee will put free software out of range for users who don't have a lot of money. With proprietary software, a high price does exactly that—but free software is different.

> The difference is that free software naturally tends to spread around, and there are many ways to get it.

> Software hoarders try their damnedest to stop you from running a proprietary program without paying the standard price. If this price is high, that does make it hard for some users to use the program.

I think that baking a license verification function into code qualifies as "trying their damnedest to stop you from running it", which is why I say they're treating it like proprietary software.

> With free software, users don't have to pay the distribution fee in order to use the software. They can copy the program from a friend who has a copy, or with the help of a friend who has network access. Or several users can join together, split the price of one CD-ROM, then each in turn can install the software. A high CD-ROM price is not a major obstacle when the software is free.

I'm not totally sure when this was written, but the mention of CDs and "a friend who has network access" makes me think that these suggestions were made before internet access became ubiquitous among computer users. And because of that ubiquitous internet access, I don't think that charging a distribution fee is effective anymore. Distribution is expected to be free and the only way to get people to pay for it is to hide the fact that they can share the software and/or prevent that sharing with license-keys and DRM.

**Comment by mAAdhaTTah** [comment]
> I think that baking a license verification function into code qualifies as "trying their damnedest to stop you from running it", which is why I say they're treating it like proprietary software.

Yup, and because of the Four Freedoms, you can modify that source code and redistribute it, as you have done.

And if your sole argument is the licensing phone home is against Free Software, I'd have some sympathy. I don't agree, but I get the argument. However, the argument you seem to be making is "Selling Free Software is against the principles of Free Software", which is demonstrably false.

> And because of that ubiquitous internet access, I don't think that charging a distribution fee is effective anymore. Distribution is expected to be free and the only way to get people to pay for it is to hide the fact that they can share the software and/or prevent that sharing with license-keys and DRM.

Whether you _think_ it's effective or not is irrelevant, as is the year this article was written. Whether the distribution is happening via CD-ROM or Internet doesn't matter; this is a _principle_ about distribution and the sale of software, and the _principle_ is selling Free Software is well within the principles/ethics of Free Software. If you want to argue that selling Free Software is unethical, you are free to do so, but you are no longer arguing for Free Software principles, but your own. Which is fine, but is not the stance you appear to be taking.

**Comment by slang800** [comment]
> However, the argument you seem to be making is "Selling Free Software is against the principles of Free Software", which is demonstrably false.

and

> If you want to argue that selling Free Software is unethical, you are free to do so

I'm sorry if I gave that impression, but that is not the point I am making. Like I said a few comments ago, "I'm not complaining _that_ they are making money off GPL'd code, I'm complaining about _how_ they are making money". If they were merely charging for downloads or CDs, I wouldn't say they are "hiding from the GPL" or that their business model is "antithetical to the _spirit_ of the GPL". The part that I don't like is that they use DRM to enforce their license-key fees and avoid telling users about their rights.

Obviously none of that is unlawful - it's just kinda shady. They aren't _required_ to tell users about their four essential freedoms, or make software as easy to use a possible, but I'd certainly have more respect for them if they did.

**Comment by andrewmclagan** [comment]
you guys should read this:

**bring-kindness-back-to-open-source**

https://medium.com/@shanselman/bring-kindness-back-to-open-source-90ed7d3ac76b#.a7bsefz7t

**Comment by andrewmclagan** [comment]
But for a debate, I personally endorse the model of premium GPL software. That being software that is active open-source, then charging for extensions upon that. Although charging for the base open-source GPL project without any work on top is really just gouging, and somewhat taking people for granted in my books.

There are allot of crazy laws in this world, does not mean they are right.

**Comment by mAAdhaTTah** [comment]
@andrewmclagan That's fair. I'm much more compassionate when reviewing others' code, but I take principles like these pretty seriously. I apologize for some of my harshness, but some of @slang800's earlier statements rubbed me the wrong way (e.g. GPL'd code that's being sold doesn't need to be "freed"; it's already free by virtue of it being GPL'd).

> Rather than giving back to the community that they stand on, they charge absurd yearly fees, build DRM into their product, and attempt to take me down with copyright.

I apologize for some of my harshness, but this @slang800 earlier statement rubbed me the wrong way. The only thing in that list that is worthy of criticism is the DRM/license key phone home. The other two points are well within DB's rights/ethics and was the core of what I was pushing back on.

**Comment by mindsize** [comment]
I may be a bit harsh at times when it comes to defending developers I feel are being wronged. I simply don't believe removing license code from a premium plugin and then abandoning the repo without keeping cadence with updates or creating anything new provides any value to the community. That's my whole issue here. If this was just a fork of a public repo, then more power to you. It's not. Delete the repo if you aren't going to maintain it. It's a disservice to those who want updates or support. At this point the only reason it exists is because somebody got butt hurt when they infringed on a copyright and got called on it.

**Comment by mAAdhaTTah** [comment]
@mindsize I disagree with that too. He's already created value by making the plugin available to a whole class of people, (e.g. Hobbyists like myself) who might otherwise not have access to a plugin like this. We, as consumers of an open source project, like to place a lot of obligations on the heads of those who open-source their work, but we're basically asking those who are working for free already to do more free work. 

So unless we as consumers are willing and able to get involved in a project, I think it's often unfair of us to demand more from those who are already giving a lot for no recompense. 

That isn't to say open source stewards have no obligation to the community, but that we often demand too much of them without being willing to give back. It's a two-way street; if we're not willing to give to a project, I don't see why we should feel entitled to more from it.

**Comment by mindsize** [comment]
The public repository from Delicious Brains is here, minus the premium
features: https://github.com/deliciousbrains/wp-migrate-db

**Comment by andrewmclagan** [comment]
just for interest:

https://github.com/wp-sync-db/wp-sync-db  << `Updated 3 days ago`

https://github.com/deliciousbrains/wp-migrate-db << `Updated 4 months ago`

**Comment by mindsize** [comment]
It looks like the only change 3 days ago was an update to the readme.md. The code itself hasn't been touched since May 5 2015, as far as I can tell. That's the last commit before the readme change.

**Comment by andrewmclagan** [comment]
Objectively `wp-sync-db/wp-sync-db` has a total of 126 commits. Whereas `deliciousbrains/wp-migrate-db` only has a total of 48 commits.

Commits are a good measure of activity, although they also reflect the git practices of the repo / devs.

**Comment by andrewmclagan** [comment]
A feature that would set this repo apart from others is the ability to sync to S3 or similar cloud storage :-)

**Comment by mindsize** [comment]
And if new development that innovates without just duplicating WP Migrate
DB Pro happens on this repo, I will finally feel that it has worth and
isn't just a vendetta... especially considering the fact that the owner of
this repo isn't even doing WordPress work anymore.

**Comment by andrewmclagan** [comment]
(Y) yeah

**Comment by slang800** [comment]
Gonna close this since I'm finally getting some time to update this repo. Feel free to continue the discussion though.

**Comment by mAAdhaTTah** [comment]
@slang800 After you've done some work on it, tagging a release so I can lock my composer versions to it would be really helpful :). I've been using Git shas for now; composer doesn't pick up version tags from before it was added to packagist.
